// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPortal.Identity.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NewsPortal.Identity.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190816125109_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NewsPortal.Identity.Database.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("7af58215-28e5-400f-ab60-2e3c3d3b9759"),
                            Login = "nikita@mail.ru",
                            Password = "AQAAAAEAACcQAAAAEE/CxB9Zs0P1T2bwduuslra/qJWnyIniUw6BDOTT15MPtzJhgvI7HFya3kSdv7GEMQ=="
                        },
                        new
                        {
                            Guid = new Guid("00a35180-51ef-4219-9d91-0f82d12202ef"),
                            Login = "ivan@mail.ru",
                            Password = "654321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
