// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPortal.Identity.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NewsPortal.Identity.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190819073721_fix1")]
    partial class fix1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NewsPortal.Identity.Database.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("9d0bbacb-968f-49cd-afc2-ce55eac11def"),
                            Login = "nikita@mail.ru",
                            Password = "AQAAAAEAACcQAAAAEH9+83KP84WPdlpit90WJkFoXxe9YNsoy4JZ7g25B5M6PgR8tOs2rTc5tthPPVawCA=="
                        },
                        new
                        {
                            Guid = new Guid("68bab636-8213-4424-b00f-07ae5a96d021"),
                            Login = "ivan@mail.ru",
                            Password = "AQAAAAEAACcQAAAAEF+a2Z0qt0qOqXhsuvRhg/mNRDzIOak8ZDCZzeapIxiJutwkVgk3w1seATSnpLbGpA=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
