// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPortal.Identity.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NewsPortal.Identity.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190816125347_user1")]
    partial class user1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NewsPortal.Identity.Database.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("53411741-42b6-4808-9414-b8d884cd5da3"),
                            Login = "nikita@mail.ru",
                            Password = "AQAAAAEAACcQAAAAEJ+oiz9BOPiMSOv0Bxh6dRhV+Y9oISN9teDEinIZ991bMR1rnm4RhkcOAHwY+UUx1Q=="
                        },
                        new
                        {
                            Guid = new Guid("120d7266-a633-4bfa-90a6-84448af2990f"),
                            Login = "ivan@mail.ru",
                            Password = "654321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
