// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPortal.Identity.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NewsPortal.Identity.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190816125817_user")]
    partial class user
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NewsPortal.Identity.Database.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("cff8059b-91ee-4394-80a8-feb44fa86b9c"),
                            Login = "nikita@mail.ru",
                            Password = "AQAAAAEAACcQAAAAEEPkcr+Hj00NbC3ANqytDfCD+9nSlp1Lssl19Qkh9T41xSIB2Iq23ic3hjVsSiI5+w=="
                        },
                        new
                        {
                            Guid = new Guid("1f9d065b-1077-4b9c-aa57-e9fd26881cda"),
                            Login = "ivan@mail.ru",
                            Password = "AQAAAAEAACcQAAAAEB+jLnAl1tv/JmG5jiZgLGahAwYoAUBm/mEGTh4qW8favHXOMVQwpcZCJ/sx1dxtbg=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
